name: tinox
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.2.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.3
  app_tracking_transparency: ^2.0.4
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^10.0.3
  appsflyer_sdk: 
  url_launcher: ^6.1.10
  flutter_inappwebview: ^5.8.0
  fl_chart: ^0.69.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  win32: ^5.6.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    # SF-Pro-Display
    - family: SFR
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf